# Generated by Django 6.1 on 2026-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_created_at_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_option',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
