# Generated by Django 6.0.7 on 2026-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='image',
            field=models.ImageField(default='j1.jpg', unique=True, upload_to=''),
        ),
    ]
