"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path


# =====================================================
# BASE DIRECTORY
# =====================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =====================================================
# SECURITY
# =====================================================

SECRET_KEY = 'django-insecure-&72-6b^-#u4&$ku_(u+_#7^i5o5qp9imjwcg+a^^9g+bet^p89'

DEBUG = True

ALLOWED_HOSTS = []


# =====================================================
# APPLICATIONS
# =====================================================

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'booking',
]


# =====================================================
# MIDDLEWARE
# =====================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =====================================================
# ROOT URL
# =====================================================

ROOT_URLCONF = 'myproject.urls'


# =====================================================
# TEMPLATES
# =====================================================

TEMPLATES = [

    {
        'BACKEND':
        'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# =====================================================
# WSGI
# =====================================================

WSGI_APPLICATION = 'myproject.wsgi.application'


# =====================================================
# DATABASE
# =====================================================

DATABASES = {

    'default': {

        'ENGINE':
        'django.db.backends.sqlite3',

        'NAME':
        BASE_DIR / 'db.sqlite3',
    }
}


# =====================================================
# PASSWORD VALIDATION
# =====================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =====================================================
# INTERNATIONALIZATION
# =====================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =====================================================
# STATIC FILES
# =====================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [

    BASE_DIR / 'static',
]


# =====================================================
# EMAIL CONFIGURATION
# DJANGO 6.1
# =====================================================

MAILERS = {

    'default': {

        'BACKEND':
        'django.core.mail.backends.smtp.EmailBackend',

        'OPTIONS': {

            'host':
            'smtp.gmail.com',

            'port':
            587,

            'username':
            'jenilgajjar90@gmail.com',

            'password':
            'mphc lszp rwdi zsgr',

            'use_tls':
            True,
        },
    },
}


# =====================================================
# DEFAULT EMAIL
# =====================================================

DEFAULT_FROM_EMAIL = 'jenilgajjar90@gmai.com'